server:
  port: 8080

spring:
  application:
    name: demo

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    platform: h2

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true
    url: jdbc:h2:mem:testdb
    user: "sa"
    password: ""
    schemas: demo
    locations: classpath:db/migration
    clean-on-validation-error: true
    baseline-version: 1
