apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  selector:
    matchLabels:
      app: demo-service
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: demo-service
          image: registry.net/demo/customer-service:{{ .Values.imageTag }}
          env:
            - name: WITH_DEBUGGING_ENABLED
              value: "{{ .Values.debuggingEnabled }}"
            - name: demo_DRUPAL_URL
              valueFrom:
                secretKeyRef:
                  name: service-access
                  key: url
          livenessProbe:
            httpGet:
                path: /actuator/health
                port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 32  #total of 3 min
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
